# Site settings
title: No Pain No Gain
description: 'Python / Go / Data Science'
url: 'https://alstn2468.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme : joshgerdes/jekyll-uno
disqus_shortname: https-alstn2468-github-io

disqus:
    shortname: https-alstn2468-github-io

author:
  name: 'Kim Minsu'
  email: alstn2468_@naver.com
  twitter_username: ''
  facebook_username: alstn2468
  github_username:  alstn2468
  linkedin_username:  minsu-kim-336289160

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
