# Site settings
title: 초보 개발자의 테크 블로그
description: 'Python / Go / Data Science / Deep Learning'
url: 'https://alstn2468.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme : joshgerdes/jekyll-uno

author:
  name: 'Kim Minsu'
  email: alstn2468_@naver.com
  twitter_username: ''
  facebook_username: profile.php?id=100003769223078
  github_username:  alstn2468
  linkedin_username:  minsu-kim-336289160

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
